### ISSUE TITLE
Need favicon.ico for browsers

### ISSUE THREAD

**Issue by mdlayher** [einsteinx2/WaveBoxWebClient#1]
This will heavily cut down on 404 errors in the log.  Thanks guys!

**Comment by mdlayher** [comment]
Here's a really crappy one I got from an online generator.  We may need something more square.

![favicon](https://f.cloud.github.com/assets/1926905/828072/e0817cce-f0aa-11e2-976a-ec78e5298bfc.png)

**Comment by justindhill** [comment]
I'll mention this to Tino.

**Comment by mdlayher** [comment]
Resolved as of commit 1cee9e13a1bcb7341c5128effb8c62f65656a8ba.
