### ISSUE TITLE
Albums in Artists Section Blank

### ISSUE THREAD

**Issue by brygui** [einsteinx2/WaveBoxWebClient#8]
For a week or so now the Albums for Artists no longer populate. I am able to see all the Artists themselves, but when I click on one, no albums are listed. Folder view show everything properly. Not sure if this is a known issue. 

Edit: After messing around with it a bunch, noticed that Wavebox was generating an updated config, once I deleted my config and have WaveBox recreate it, it started working. This issue can be closed.

**Comment by justindhill** [comment]
Hey @byronnnn,

I realize you closed this issue, but I've rectified the underlying cause of it. Thanks for reporting this!

**Comment by brygui** [comment]
@justindhill It was interesting because it was working briefly, but I was traveling and didn't use it much after I rebuilt everything. I was going to reopen this today, because I actually realized what it was doing. It was creating an album for each track, and was just taking a really long time to load.  Just updated and it is displaying properly. Thanks!

**Comment by justindhill** [comment]
Sure thing!
